# Generated by Django 6.0.4 on 2026-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=190)),
                ('phone', models.IntegerField(max_length=11)),
                ('password', models.CharField(max_length=140)),
                ('confirm_password', models.CharField(max_length=140)),
            ],
        ),
    ]
