# Generated by Django 6.0.4 on 2026-04-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accounts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='phone',
        ),
    ]
