# Generated by Django 6.0.4 on 2026-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_accounts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
