# Generated by Django 6.0.4 on 2026-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accounts_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.CharField(max_length=150),
        ),
    ]
